version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
    timezone: US/Arizona
  open-pull-requests-limit: 3
  assignees:
  - peterdemartini
  ignore:
  - dependency-name: elasticsearch
    versions:
    - "> 15.5.0"
  - dependency-name: "@types/node"
    versions:
    - "> 14.14.37"
  - dependency-name: "@terascope/data-mate"
    versions:
    - 0.21.0
    - 0.25.1
    - 0.25.2
    - 0.25.4
    - 0.27.3
  - dependency-name: "@terascope/elasticsearch-api"
    versions:
    - 2.18.3
    - 2.18.7
  - dependency-name: "@terascope/data-types"
    versions:
    - 0.27.5
    - 0.27.7
  - dependency-name: "@terascope/types"
    versions:
    - 0.7.2
  - dependency-name: "@types/node"
    versions:
    - 14.14.25
    - 14.14.28
    - 14.14.31
    - 14.14.32
    - 14.14.34
    - 14.14.35
    - 14.14.37
  - dependency-name: "@terascope/utils"
    versions:
    - 0.35.0
    - 0.36.3
    - 0.36.4
    - 0.36.5
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
  - dependency-name: "@terascope/job-components"
    versions:
    - 0.45.0
