version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      time: '04:00'
      timezone: US/Arizona
    open-pull-requests-limit: 0
    assignees:
      - sotojn
      - busma13
    # ignore:
    #   - dependency-name: elasticsearch
    #     versions:
    #       - '> 15.5.0'
    #   - dependency-name: '@types/node'
    #     versions:
    #       - '>= 17.0.0'
  - package-ecosystem: npm
    directory: '/website'
    schedule:
      interval: monthly
      time: '04:00'
      timezone: US/Arizona
    ignore:
      - dependency-name: "*"
    open-pull-requests-limit: 0
    assignees:
      - godber
      - sotojn
      - busma13
