version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      time: '04:00'
      timezone: US/Arizona
    open-pull-requests-limit: 6
    assignees:
      - godber
      - jsnoble
    ignore:
      - dependency-name: elasticsearch
        versions:
          - '> 15.5.0'
      - dependency-name: '@types/node'
        versions:
          - '>= 17.0.0'
