# set the dist to bionic
dist: bionic
language: node_js
node_js:
  - '10.19'
  - '12.18'
os:
  - linux
  - osx
branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+/
if: NOT (branch = master AND type = push AND tag IS blank AND os = osx)
cache:
  npm: false
  yarn: false
services:
  - docker
env:
  - ELASTICSEARCH_VERSION=5.6.0
  - ELASTICSEARCH_VERSION=6.8.6
  - ELASTICSEARCH_VERSION=7.2.1
jobs:
  exclude:
  - os: osx
    env: ELASTICSEARCH_VERSION=7.2.1
before_script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        docker run -d --publish "9200:9200"
            --env "ES_JAVA_OPTS=-Xms256m -Xmx256m"
            --env "network.host=0.0.0.0"
            --env "discovery.type=single-node"
            "blacktop/elasticsearch:$ELASTICSEARCH_VERSION";
    else
        echo "* skipping docker run for macos...";
    fi
  - yarn build
  - yarn global add teraslice-cli
script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        yarn test;
    else
        echo "* skipping tests for macos...";
    fi
  - yarn lint
  - teraslice-cli assets build
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: build/*.zip
  skip_cleanup: true
  on:
    tags: true
