# set the dist to bionic
dist: bionic
language: node_js
node_js:
  - '12.22'
  - '14.17'
os:
  - linux
  - osx
branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+/
addons:
  apt:
    packages:
      - jq
if: NOT (branch = master AND type = push AND tag IS blank AND os = osx)
cache:
  npm: false
  yarn: false
services:
  - docker
env:
  - ELASTICSEARCH_VERSION=5.6
  - ELASTICSEARCH_VERSION=6.8.6
  - ELASTICSEARCH_VERSION=7.2.1
jobs:
  exclude:
  # Don't build es 7 on osx because it is redundant
  - os: osx
    env: ELASTICSEARCH_VERSION=7.2.1
  # Don't build es 5 on node 12
  - node_js: '12.20'
    env: ELASTICSEARCH_VERSION=5.6
before_script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        docker run -d --publish "9200:9200"
            --env "ES_JAVA_OPTS=-Xms256m -Xmx256m"
            --env "network.host=0.0.0.0"
            --env "discovery.type=single-node"
            "blacktop/elasticsearch:$ELASTICSEARCH_VERSION";
    else
        echo "* skipping docker run for macos...";
    fi
  - yarn build
  - yarn global add teraslice-cli
script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        yarn test:all;
    else
        echo "* skipping tests for macos...";
    fi
  - yarn lint
  - teraslice-cli -v
  - teraslice-cli assets build
  - teraslice-cli assets build --bundle
after_success:
  - bash <(curl -s https://codecov.io/bash)
before_deploy:
  - teraslice-cli assets build
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
deploy:
  - provider: script
    skip_cleanup: true
    script: yarn publish:changed
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
  - provider: releases
    api_key: $GITHUB_TOKEN
    prerelease: true
    file_glob: true
    file: build/*.zip
    skip_cleanup: true
    on:
      tags: true
