# set the dist to bionic
dist: bionic
language: node_js
node_js:
  - '10.19'
  - '12.17'
os:
  - linux
  - osx
branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+/
if: NOT (branch = master AND type = push AND tag IS blank AND os = osx)
cache:
  npm: false
  yarn: false
services:
  - docker
env:
  - ELASTICSEARCH_VERSION=6.8.6
  - ELASTICSEARCH_VERSION=7.2.1
before_script:
  - '[[ $TRAVIS_OS_NAME == "linux" ]] && docker run -d
        --publish 9200:9200
        --env "ES_JAVA_OPTS=-Xms256m -Xmx256m"
        --env "network.host=0.0.0.0"
        --env "discovery.type=single-node"
        blacktop/elasticsearch:$ELASTICSEARCH_VERSION'
script:
  - '[[ $TRAVIS_OS_NAME == "linux" ]] && yarn test'
  - '[[ $TRAVIS_OS_NAME == "osx" ]] && echo "* skipping tests for macos"'
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - yarn lint
  - yarn global add teraslice-cli
  - teraslice-cli assets build
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: build/*.zip
  skip_cleanup: true
  on:
    tags: true
