# set the dist to bionic
dist: bionic
language: node_js
node_js:
  - '10.19'
  - '12.17'
os:
  - linux
  - osx
branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+/
if: NOT (branch = master AND type = push AND tag IS blank AND os = osx)
cache:
  npm: false
  yarn: false
env:
  - ELASTICSEARCH_VERSION=6.8.6
  - ELASTICSEARCH_VERSION=7.2.1
before_script:
  - curl -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/$ELASTICSEARCH_VERSION/elasticsearch-$ELASTICSEARCH_VERSION.deb
  - sudo dpkg -i --force-confnew elasticsearch-$ELASTICSEARCH_VERSION.deb
  - sudo service elasticsearch restart
  - sleep 10
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - yarn lint
  - yarn global add teraslice-cli
  - teraslice-cli assets build
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: build/*.zip
  skip_cleanup: true
  on:
    tags: true
