// NOTE: This code is auto-generated by `teraslice-cli assets registry`
// any manual changes will be lost next time this gets auto-generated.

import ElasticsearchBulk from '../src/elasticsearch_bulk/processor.js';
import ElasticsearchBulkSchema from '../src/elasticsearch_bulk/schema.js';

import ElasticsearchReaderFetcher from '../src/elasticsearch_reader/fetcher.js';
import ElasticsearchReaderSchema from '../src/elasticsearch_reader/schema.js';
import ElasticsearchReaderSlicer from '../src/elasticsearch_reader/slicer.js';

import ElasticsearchReaderAPI from '../src/elasticsearch_reader_api/api.js';
import ElasticsearchReaderAPISchema from '../src/elasticsearch_reader_api/schema.js';

import ElasticsearchSenderAPI from '../src/elasticsearch_sender_api/api.js';
import ElasticsearchSenderAPISchema from '../src/elasticsearch_sender_api/schema.js';

import ElasticsearchStateStorageAPI from '../src/elasticsearch_state_storage/api.js';
import ElasticsearchStateStorageSchema from '../src/elasticsearch_state_storage/schema.js';

import IdReaderFetcher from '../src/id_reader/fetcher.js';
import IdReaderSchema from '../src/id_reader/schema.js';
import IdReaderSlicer from '../src/id_reader/slicer.js';

import SpacesReaderFetcher from '../src/spaces_reader/fetcher.js';
import SpacesReaderSchema from '../src/spaces_reader/schema.js';
import SpacesReaderSlicer from '../src/spaces_reader/slicer.js';

import SpacesReaderAPI from '../src/spaces_reader_api/api.js';
import SpacesReaderAPISchema from '../src/spaces_reader_api/schema.js';

export const ASSETS = {
    elasticsearch_bulk: {
        Processor: ElasticsearchBulk,
        Schema: ElasticsearchBulkSchema,
    },
    elasticsearch_reader: {
        Fetcher: ElasticsearchReaderFetcher,
        Schema: ElasticsearchReaderSchema,
        Slicer: ElasticsearchReaderSlicer,
    },
    elasticsearch_reader_api: {
        API: ElasticsearchReaderAPI,
        Schema: ElasticsearchReaderAPISchema,
    },
    elasticsearch_sender_api: {
        API: ElasticsearchSenderAPI,
        Schema: ElasticsearchSenderAPISchema,
    },
    elasticsearch_state_storage: {
        API: ElasticsearchStateStorageAPI,
        Schema: ElasticsearchStateStorageSchema,
    },
    id_reader: {
        Fetcher: IdReaderFetcher,
        Schema: IdReaderSchema,
        Slicer: IdReaderSlicer,
    },
    spaces_reader: {
        Fetcher: SpacesReaderFetcher,
        Schema: SpacesReaderSchema,
        Slicer: SpacesReaderSlicer,
    },
    spaces_reader_api: {
        API: SpacesReaderAPI,
        Schema: SpacesReaderAPISchema,
    },
};
