const { TEST_INDEX_PREFIX = 'es_assets_', ELASTICSEARCH_HOST = 'http://localhost:9200', ELASTICSEARCH_API_VERSION = '6.5' } = process.env;

export { TEST_INDEX_PREFIX, ELASTICSEARCH_HOST, ELASTICSEARCH_API_VERSION };
