name: Daily Docker Cache

on:
  schedule:
    - cron: '0 11 30 * 1-5' # Monday - Friday at 5am Arizona Time
  workflow_dispatch:

jobs:
  call-refresh-docker-cache-workflow:
    uses: terascope/workflows/.github/workflows/refresh-docker-cache.yml@fbd0c1372ed26dffeff757a94b3615cf370b866f
    secrets: inherit
